title: "Thairlan Anjos | Notes"
author: "Thairlan Anjos..."
description: "Hello, welcome to my blog, here I publish every week lifestyle notes, ux design, articles and book summaries on technology and web development."

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "contact@thairlananjos.com"
twitter_username: "ThairlanAnjos"
#github_username: "githubuser"
#linkedin_username: "ThairlanAnjos"
#facebook_username: username
#flickr_username: username
instagram_username: "ThairlanAnjos"
#pinterest_username: username
#youtube_username: "ThairlanAnjos"
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
